name: decrypt_enviroment

on:
  push:
    branches:
      - main
      - develop
      
jobs:
  decrypt_enviroment:
    name: decrypt env
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Decrypt env.json.gpg
        run: ./decryptenv.sh
        env:
          TEST_SECRET_VALUE: ${{ secrets.TEST_SECRET_VALUE }}
